{
  "openapi": "3.0.1",
  "info": {
    "title": "BookingProject.API",
    "version": "v1"
  },
  "paths": {
    "/Booking/list/{currentPage}": {
      "get": {
        "tags": ["Booking"],
        "parameters": [
          {
            "name": "currentPage",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 1
            }
          },
          {
            "name": "user_name",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "user_last_name",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "apartment_name",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "confirmend",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/BookingViewPaginationModel"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BookingViewPaginationModel"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/BookingViewPaginationModel"
                }
              }
            }
          }
        }
      }
    },
    "/Booking/getById/{id}": {
      "get": {
        "tags": ["Booking"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/BookingModel"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BookingModel"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/BookingModel"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/Booking/delete/{id}": {
      "delete": {
        "tags": ["Booking"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/Booking/update/{id}": {
      "put": {
        "tags": ["Booking"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BookingUpdateModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/BookingUpdateModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/BookingUpdateModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/BookingUpdateModel"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BookingUpdateModel"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/BookingUpdateModel"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/Booking/create": {
      "post": {
        "tags": ["Booking"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BookingAddModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/BookingAddModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/BookingAddModel"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/BookingModel"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BookingModel"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/BookingModel"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "BookingAddModel": {
        "required": ["apartment_id", "booked_for", "starts_at"],
        "type": "object",
        "properties": {
          "user_email": {
            "type": "string",
            "nullable": true
          },
          "starts_at": {
            "type": "string"
          },
          "booked_for": {
            "type": "integer",
            "format": "int32"
          },
          "apartment_id": {
            "type": "integer",
            "format": "int32"
          },
          "confirmed": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      },
      "BookingModel": {
        "type": "object",
        "properties": {
          "user_fullname": {
            "type": "string",
            "nullable": true
          },
          "user_email": {
            "type": "string",
            "nullable": true
          },
          "booking_id": {
            "type": "integer",
            "format": "int32"
          },
          "starts_at": {
            "type": "string",
            "nullable": true
          },
          "booked_at": {
            "type": "string",
            "nullable": true
          },
          "booked_for": {
            "type": "integer",
            "format": "int32"
          },
          "apartment_name": {
            "type": "string",
            "nullable": true
          },
          "confirmed": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      },
      "BookingUpdateModel": {
        "type": "object",
        "properties": {
          "starts_at": {
            "type": "string",
            "nullable": true
          },
          "booked_for": {
            "type": "integer",
            "format": "int32"
          },
          "confirmed": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      },
      "BookingViewModel": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string",
            "nullable": true
          },
          "last_name": {
            "type": "string",
            "nullable": true
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "phone": {
            "type": "string",
            "nullable": true
          },
          "booking_id": {
            "type": "integer",
            "format": "int32"
          },
          "starts_at": {
            "type": "string",
            "nullable": true
          },
          "booked_at": {
            "type": "string",
            "nullable": true
          },
          "confirmed": {
            "type": "integer",
            "format": "int32"
          },
          "apartment_name": {
            "type": "string",
            "nullable": true
          },
          "apartment_address": {
            "type": "string",
            "nullable": true
          },
          "apartment_zip_code": {
            "type": "string",
            "nullable": true
          },
          "apartment_city": {
            "type": "string",
            "nullable": true
          },
          "apartment_country": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "BookingViewPaginationModel": {
        "type": "object",
        "properties": {
          "bookingList": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/BookingViewModel"
            },
            "nullable": true
          },
          "currentPageIndex": {
            "type": "integer",
            "format": "int32"
          },
          "pageCount": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      }
    }
  }
}
